name: backboard
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=9.2=0
  - pip=19.3.1
  - python=3.7.6
  - pytorch=1.4.0=py3.7_cuda9.2.148_cudnn7.6.3_0
  - torchvision=0.5.0=py37_cu92
  - pip:
      - -r requirements.txt
      - -e .
