name: cockpit
dependencies:
  - pip=19.3.1
  - python=3.7.6
  - conda-forge::black
  - conda-forge::darglint
  - conda-forge::flake8
  - conda-forge::flake8-bugbear
  - conda-forge::flake8-comprehensions
  - conda-forge::isort
  - conda-forge::palettable
  - conda-forge::pydocstyle
  - conda-forge::pytest
  - conda-forge::pytest-cov
  - conda-forge::pytest-benchmark
  - conda-forge::m2r2
  - conda-forge::sphinx
  - conda-forge::sphinx-automodapi
  - conda-forge::sphinx_rtd_theme
  - conda-forge::tikzplotlib
  - pip:
    - memory-profiler
    - pre-commit
    - graphviz
    - git+https://git@github.com/fsschneider/DeepOBS.git@develop#egg=deepobs
    - git+https://git@github.com/f-dangel/backobs.git@development#egg=backobs
    - -e .
