name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - development
      - master


jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        pip install requests
        pip install coveralls
        pip install .
        pip install git+https://git@github.com/fsschneider/DeepOBS.git@develop#egg=deepobs
        pip install git+https://git@github.com/f-dangel/backobs.git@development#egg=backobs
    - name: Run pytest
      run: |
        make test
    - name: Test coveralls
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}